import type { Metadata } from 'next'
import './globals.css'
import I18nProvider from '@/components/providers/I18nProvider'
import SessionProvider from '@/components/providers/SessionProvider'
import { AppProviders } from '@/components/providers/AppProviders'
import MainLayout from '@/components/layout/MainLayout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params

  return (
    <html lang={locale} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <I18nProvider locale={locale}>
          <SessionProvider>
            <AppProviders>
              <MainLayout>{children}</MainLayout>
            </AppProviders>
          </SessionProvider>
        </I18nProvider>
      </body>
    </html>
  )
}
