import type { Metadata } from 'next'
import './globals.css'
import I18nProvider from '@/components/providers/I18nProvider'
import SessionProvider from '@/components/providers/SessionProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const { locale } = await params

  return (
    <I18nProvider locale={locale}>
      <SessionProvider>
        <main>{children}</main>
      </SessionProvider>
    </I18nProvider>
  )
}
